export const ADD_TODO = 'ADD_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const TOGGLE_PROCESSING_STATE = 'TOGGLE_PROCESSING_STATE';
export const TOGGLE_OFFLINE_SAVE = 'TOGGLE_OFFLINE_SAVE';
